// web/admin/src/components/AdminHeader.tsx
import { format } from "date-fns";
import { useNavigate } from "react-router-dom";
import { AppBar, Toolbar, Typography, Button, Container } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import { createAdminApiClient } from "../admin_api";

const api = createAdminApiClient();

export default function AdminHeader() {
	const navigate = useNavigate();

	async function handleNewEntry() {
		try {
			// Generate a placeholder title with current date/time
			const now = new Date();
			const placeholderTitle = format(now, "'New Entry' yyyy-MM-dd HH-mm-ss");

			const data = await api.createEntry({ title: placeholderTitle });
			console.log(`New entry created: ${data.path}`);
			navigate(`/admin/entry/${data.path}`);
		} catch (e) {
			console.error("Error creating new entry:", e);
			alert("Failed to create new entry");
		}
	}

	return (
		<AppBar position="fixed">
			<Container maxWidth="xl">
				<Toolbar disableGutters>
					<Typography
						variant="h6"
						component="a"
						href="/admin/"
						sx={{
							flexGrow: 1,
							textDecoration: "none",
							color: "inherit",
							fontWeight: 700,
						}}
					>
						Blog Admin
					</Typography>
					<Button
						color="inherit"
						onClick={handleNewEntry}
						startIcon={<AddIcon />}
						variant="outlined"
						sx={{ borderColor: "rgba(255, 255, 255, 0.5)" }}
					>
						New Entry
					</Button>
				</Toolbar>
			</Container>
		</AppBar>
	);
}

// server/admin/frontend/src/components/AdminHeader.svelte
<script lang="ts">
import { createAdminApiClient } from "../admin_api";

const api = createAdminApiClient();

async function handleNewEntry() {
	try {
		const data = await api.createEntry({ createEntryRequest: {} });
		console.log(`New entry created: ${data.path}`);
		location.href = `/admin/entry/${data.path}`;
	} catch (e) {
		console.error("Error creating new entry:", e);
		alert("Failed to create new entry");
	}
}
</script>

<header>
	<div class="container">
		<!-- トップページへのリンク -->
		<a href="/admin/" class="text-xl">Blog Admin</a>

		<!-- ナビゲーションリンク -->
		<nav>
			<button onclick={handleNewEntry}>New Entry</button>
		</nav>
	</div>
</header>

<style>
	header {
		position: fixed;
		left: 0;
		top: 0;
		z-index: 10;
		width: 100%;
		background-color: #d92706;
		color: white;
		height: 62px;
		vertical-align: middle;

		font-family: 'Hiragino Kaku Gothic ProN', 'Meiryo', sans-serif;
	}

	.container {
		max-width: 1200px;
		margin: 0 auto;
	}

	a {
		display: block;
		float: left;
		text-decoration: none;
		color: white;
		padding: 8px;
	}

	a:hover {
		text-decoration: underline;
		cursor: pointer;
	}

	.text-xl {
		font-size: 1.25rem;
		font-weight: bold;
	}

	nav {
		float: right;
	}

	button {
		background: none;
		border: none;
		color: white;
		text-decoration: none;
		cursor: pointer;
		font: inherit;
	}

	button:hover {
		text-decoration: underline;
	}
</style>
