// web/admin/src/components/CardItem.tsx
import type React from "react";
import { Card, CardContent, Typography, Box } from "@mui/material";

interface CardItemProps {
	title?: string;
	content?: string;
	onClick?: (event: React.MouseEvent) => void;
	backgroundColor?: string;
	color?: string;
	imgSrc?: string | null;
}

export default function CardItem({
	title,
	content = "",
	onClick = () => {},
	backgroundColor = "#f6f6f6",
	color = "#0f0f0f",
	imgSrc,
}: CardItemProps) {
	return (
		<Card
			sx={{
				width: 170,
				height: 170,
				display: "flex",
				flexDirection: "column",
				backgroundColor,
				color,
				cursor: "pointer",
				"&:hover": {
					boxShadow: 3,
				},
			}}
			onClick={onClick}
		>
			<CardContent
				sx={{
					height: "100%",
					display: "flex",
					flexDirection: "column",
					p: 1.5,
				}}
			>
				{title && (
					<Typography
						variant="body2"
						component="h2"
						sx={{
							fontWeight: 600,
							fontSize: "0.875rem",
							overflow: "hidden",
							textOverflow: "ellipsis",
							display: "-webkit-box",
							WebkitLineClamp: 2,
							WebkitBoxOrient: "vertical",
							mb: 0.5,
						}}
					>
						{title}
					</Typography>
				)}
				{imgSrc && (
					<Box
						component="img"
						src={imgSrc}
						alt={title || "Entry image"}
						sx={{
							width: "100%",
							height: 60,
							objectFit: "cover",
							borderRadius: 1,
							mb: 0.5,
						}}
					/>
				)}
				{content && (
					<Typography
						variant="caption"
						color="text.secondary"
						sx={{
							fontSize: "0.75rem",
							overflow: "hidden",
							textOverflow: "ellipsis",
							display: "-webkit-box",
							WebkitLineClamp: imgSrc ? 3 : 6,
							WebkitBoxOrient: "vertical",
							flexGrow: 1,
						}}
					>
						{content}
					</Typography>
				)}
			</CardContent>
		</Card>
	);
}

// server/admin/frontend/src/components/CardItem.svelte
<script lang="ts">
const {
	title,
	content = "",
	onClick = () => {},
	backgroundColor = "#f6f6f6",
	color = "#0f0f0f",
	imgSrc = undefined,
}: {
	title: string | undefined;
	content?: string | undefined;
	onClick?: (event: MouseEvent) => void;
	backgroundColor?: string;
	color?: string;
	imgSrc?: string | undefined | null;
} = $props();
</script>

<button class="card" style:background-color={backgroundColor} style:color onclick={onClick}>
	{#if title}
		<span class="title">{title}</span>
	{/if}
	{#if imgSrc}
		<!-- eslint-disable-next-line a11y-img-redundant-alt -->
		<img
			src={imgSrc}
			alt="great one"
			style="max-width: 100%;max-height: 100%; border: 1px solid #000;"
		/>
	{/if}
	{#if title}
		<span class="content">{content}</span>
	{/if}
</button>

<style>
	.card {
		display: flex; /* Flexboxを有効にします */
		flex-direction: column; /* アイテムを縦方向に並べます */
		align-items: flex-start; /* 左寄せにします（テキストが左揃えの場合） */
		justify-content: flex-start; /* アイテムを上に寄せます */
		float: left;
		width: 150px;
		height: 150px;
		margin: 2px;
		padding: 4px;
		overflow-y: hidden;
		border-radius: 2px;
		text-align: left;
		vertical-align: top;
		overflow-x: hidden;
		cursor: pointer;
	}

	.title {
		font-size: 0.875rem;
		font-weight: bold;
		word-break: break-all;
	}

	.content {
		margin-top: 4px;
		color: #4b5563;
		font-size: 0.675rem;
	}
</style>
