// server/admin/frontend/src/components/LinkPallet.svelte
<script lang="ts">
import AdminEntryCardItem from "./AdminEntryCardItem.svelte";
import CardItem from "./CardItem.svelte";
import type { LinkPalletData } from "../generated-client/model";
import { createAdminApiClient } from "../admin_api";

const { linkPallet }: { linkPallet: LinkPalletData } = $props();

const api = createAdminApiClient();

function createNewEntry(title: string) {
	api
		.createEntry({
			createEntryRequest: { title },
		})
		.then((data) => {
			location.href = `/admin/entry/${data.Path}`;
		})
		.catch((err) => {
			console.error("Error creating new entry:", err);
			alert("Failed to create new entry");
		});
}
</script>

<div class="link-pallet">
	<div class="one-hop-link">
		{#each linkPallet.links as link}
			<AdminEntryCardItem entry={link} />
		{/each}
	</div>
	{#each linkPallet.twohops as twohops}
		<div class="two-hop-link">
			{#if twohops.src.Title}
				<AdminEntryCardItem entry={twohops.src} backgroundColor={'yellowgreen'} />
			{:else}
				<CardItem
					onClick={() => createNewEntry(twohops.src.dstTitle)}
					title={twohops.src.dstTitle}
					content=""
					backgroundColor="#c0f6f6"
					color="gray"
				/>
			{/if}
			{#each twohops.links as link}
				<AdminEntryCardItem entry={link} />
			{/each}
		</div>
	{/each}
	{#if linkPallet.newLinks.length > 0}
		<div class="one-hop-link">
			<CardItem onClick={() => false} title="New Item" content="" backgroundColor="darkgoldenrod" />
			{#each linkPallet.newLinks as title}
				<CardItem onClick={() => createNewEntry(title)} {title} content="" color="gray" />
			{/each}
		</div>
	{/if}
</div>

<style>
	.one-hop-link {
		display: flex;
		flex-wrap: wrap;
		gap: 1rem;
		clear: both;
	}
	.two-hop-link {
		display: flex;
		flex-wrap: wrap;
		gap: 1rem;
		clear: both;
		margin-top: 1rem;
	}
</style>

// server/admin/frontend/src/components/LinkPallet.tsx
import React from "react";
import type { LinkPalletData } from "../generated-client/model";
import AdminEntryCardItem from "./AdminEntryCardItem";
import CardItem from "./CardItem";
import { createAdminApiClient } from "../admin_api";

interface LinkPalletProps {
	linkPallet: LinkPalletData;
}

const api = createAdminApiClient();

export default function LinkPallet({ linkPallet }: LinkPalletProps) {
	function createNewEntry(title: string) {
		api
			.createEntry({
				createEntryRequest: { title },
			})
			.then((data) => {
				location.href = `/admin/entry/${data.Path}`;
			})
			.catch((err) => {
				console.error("Error creating new entry:", err);
				alert("Failed to create new entry");
			});
	}

	const styles = {
		linkPallet: {},
		oneHopLink: {
			display: "flex",
			flexWrap: "wrap" as const,
			gap: "1rem",
			clear: "both" as const,
		},
		twoHopLink: {
			display: "flex",
			flexWrap: "wrap" as const,
			gap: "1rem",
			clear: "both" as const,
			marginTop: "1rem",
		},
	};

	return (
		<div style={styles.linkPallet}>
			<div style={styles.oneHopLink}>
				{linkPallet.links.map((link) => (
					<AdminEntryCardItem key={link.Path} entry={link} />
				))}
			</div>
			{linkPallet.twohops.map((twohops, index) => (
				<div key={index} style={styles.twoHopLink}>
					{twohops.src.Title ? (
						<AdminEntryCardItem
							entry={twohops.src}
							backgroundColor="yellowgreen"
						/>
					) : (
						<CardItem
							onClick={() => createNewEntry(twohops.src.dstTitle)}
							title={twohops.src.dstTitle}
							content=""
							backgroundColor="#c0f6f6"
							color="gray"
						/>
					)}
					{twohops.links.map((link) => (
						<AdminEntryCardItem key={link.Path} entry={link} />
					))}
				</div>
			))}
			{linkPallet.newLinks.length > 0 && (
				<div style={styles.oneHopLink}>
					<CardItem
						onClick={() => false}
						title="New Item"
						content=""
						backgroundColor="darkgoldenrod"
					/>
					{linkPallet.newLinks.map((title) => (
						<CardItem
							key={title}
							onClick={() => createNewEntry(title)}
							title={title}
							content=""
							color="gray"
						/>
					))}
				</div>
			)}
		</div>
	);
}
