// server/admin/frontend/src/components/MarkdownEditor.svelte
<script lang="ts">
import {
	type CompletionContext,
	autocompletion,
} from "@codemirror/autocomplete";
import { history, historyKeymap, indentWithTab } from "@codemirror/commands";
import { defaultKeymap } from "@codemirror/commands";
import { markdown, markdownLanguage } from "@codemirror/lang-markdown";
import { syntaxHighlighting } from "@codemirror/language";
import { languages } from "@codemirror/language-data";
import { EditorState, Transaction } from "@codemirror/state";
import { oneDarkHighlightStyle } from "@codemirror/theme-one-dark";
import { EditorView, keymap } from "@codemirror/view";
import { onMount } from "svelte";
import { createAdminApiClient } from "../admin_api";
import { internalLinkPlugin } from "./markdown/InternalLink";

let container: HTMLDivElement;

const api = createAdminApiClient();

const {
	initialContent = "",
	onUpdateText,
	onSave = () => {},
	existsEntryByTitle,
	onClickEntry,
	content = initialContent,
	pageTitles = [],
}: {
	initialContent: string;
	onUpdateText: (content: string) => void;
	onSave: (content: string) => void;
	existsEntryByTitle: (title: string) => boolean;
	onClickEntry: (title: string) => void;
	content: string;
	pageTitles: string[];
} = $props();

let editor: EditorView;

let isUploading: boolean = $state(false); // アップロード中の状態
let errorMessage: string = $state(""); // エラー通知メッセージ

const myCompletion = (context: CompletionContext) => {
	{
		// `[[foobar]]` style notation
		const word = context.matchBefore(/\[\[(?:(?!]].*).)*/);
		if (word) {
			console.log("Return links");
			const options = pageTitles.map((title) => {
				return {
					label: `[[${title}]]`,
					type: "keyword",
				};
			});
			return {
				from: word.from,
				options: options,
			};
		}
	}
	return null;
};

onMount(() => {
	const startState = EditorState.create({
		doc: initialContent,
		extensions: [
			internalLinkPlugin(existsEntryByTitle, onClickEntry),
			markdown({
				base: markdownLanguage,
				codeLanguages: languages,
			}),
			history(),
			syntaxHighlighting(oneDarkHighlightStyle),
			autocompletion({ override: [myCompletion], closeOnBlur: false }),
			EditorView.lineWrapping,
			keymap.of([...historyKeymap, ...defaultKeymap, indentWithTab]),
			EditorView.theme({
				".cm-editor": { height: "600px" },
				".cm-content": { overflowY: "auto" },
			}),
			EditorView.domEventHandlers({
				paste: handlePaste,
			}),
			EditorView.updateListener.of((update) => {
				if (update.changes) {
					const isUserInput = update.transactions.some(
						(tr) =>
							tr.annotation(Transaction.userEvent) !== "program" &&
							tr.docChanged,
					);
					if (isUserInput && onUpdateText) {
						onUpdateText(editor.state.doc.toString());
					}
				}
			}),
		],
	});

	editor = new EditorView({
		state: startState,
		parent: container,
	});

	$effect(() => {
		console.log("content:", content);
		if (editor && content !== editor.state.doc.toString()) {
			const transaction = editor.state.update({
				changes: {
					from: 0,
					to: editor.state.doc.length,
					insert: content,
				},
			});
			editor.dispatch(transaction);
		}
	});

	return () => {
		editor.destroy();
	};
});

function handlePaste(event: ClipboardEvent): void {
	const items = event.clipboardData?.items;
	if (!items) return;

	for (const item of items) {
		if (item.type.startsWith("image/")) {
			event.preventDefault();

			const file = item.getAsFile();
			if (file) {
				isUploading = true; // アップロード中フラグを立てる
				uploadImage(file)
					.then((url) => {
						insertMarkdownImage(url);
					})
					.catch((error) => {
						console.error("Image upload failed:", error);
						showError("Image upload failed. Please try again.");
					})
					.finally(() => {
						isUploading = false; // アップロード完了でフラグを下ろす
					});
			}
		}
	}
}

async function uploadImage(file: File): Promise<string> {
	const formData = new FormData();
	formData.append("file", file);

	try {
		const data = await api.uploadFile(formData);
		return data.url;
	} catch (e) {
		throw new Error(`Failed to upload image: ${e}`);
	}
}

function insertMarkdownImage(url: string) {
	const markdownImage = `![Image](${url})`;
	const transaction = editor.state.update({
		changes: {
			from: editor.state.selection.main.from,
			insert: markdownImage,
		},
	});
	editor.dispatch(transaction);
}

function showError(message: string) {
	errorMessage = message;
	setTimeout(() => {
		errorMessage = ""; // 7秒後にエラーメッセージを非表示
	}, 7000);
}

const handleKeyDown = (event: KeyboardEvent) => {
	if ((event.ctrlKey || event.metaKey) && event.key === "s") {
		event.preventDefault();
		onSave(editor.state.doc.toString());
	}
};
</script>

<svelte:window on:keydown={handleKeyDown} />

<div class="wrapper">
	<div bind:this={container}></div>
	{#if isUploading}
		<div class="upload-indicator">Uploading image...</div>
	{/if}
	{#if errorMessage}
		<div class="error-indicator">{errorMessage}</div>
	{/if}
</div>

<style>
	.wrapper {
		width: 100%;
		height: 100%;
	}

	.upload-indicator {
		position: fixed;
		bottom: 20px;
		right: 20px;
		background: rgba(0, 0, 0, 0.7);
		color: white;
		padding: 10px 15px;
		border-radius: 5px;
		font-size: 14px;
	}

	.error-indicator {
		position: fixed;
		bottom: 60px;
		right: 20px;
		background: rgba(255, 0, 0, 0.8);
		color: white;
		padding: 10px 15px;
		border-radius: 5px;
		font-size: 14px;
	}
</style>

// server/admin/frontend/src/components/MarkdownEditor.tsx
import { useEffect, useRef } from "react";
import { EditorState } from "@codemirror/state";
import { EditorView, keymap } from "@codemirror/view";
import { markdown } from "@codemirror/lang-markdown";
import { defaultKeymap, indentWithTab } from "@codemirror/commands";
import { oneDarkHighlightStyle } from "@codemirror/theme-one-dark";
import { syntaxHighlighting } from "@codemirror/language";

interface MarkdownEditorProps {
	initialContent?: string;
	onUpdateText?: (text: string) => void;
	onDropFiles?: (files: File[]) => Promise<string[]>;
	existsEntryByTitle?: (title: string) => boolean;
	findOrCreateEntry?: (title: string) => void;
}

export default function MarkdownEditor({
	initialContent = "",
	onUpdateText,
	onDropFiles,
}: MarkdownEditorProps) {
	const containerRef = useRef<HTMLDivElement>(null);
	const editorRef = useRef<EditorView | null>(null);
	const onUpdateTextRef = useRef(onUpdateText);
	const onDropFilesRef = useRef(onDropFiles);

	// Update the refs when callbacks change
	useEffect(() => {
		onUpdateTextRef.current = onUpdateText;
	}, [onUpdateText]);

	useEffect(() => {
		onDropFilesRef.current = onDropFiles;
	}, [onDropFiles]);

	// Initialize editor only once
	useEffect(() => {
		if (!containerRef.current) return;

		const state = EditorState.create({
			doc: initialContent,
			extensions: [
				markdown(),
				keymap.of([...defaultKeymap, indentWithTab]),
				syntaxHighlighting(oneDarkHighlightStyle),
				EditorView.updateListener.of((update) => {
					if (update.docChanged && onUpdateTextRef.current) {
						onUpdateTextRef.current(update.state.doc.toString());
					}
				}),
				EditorView.domEventHandlers({
					paste: (event, view) => {
						console.log("Paste event triggered", event);
						const items = event.clipboardData?.items;
						if (!items) return false;

						const files: File[] = [];
						for (let i = 0; i < items.length; i++) {
							const item = items[i];
							console.log("Clipboard item:", item.type);
							if (item.type.indexOf('image') !== -1) {
								const file = item.getAsFile();
								if (file) {
									files.push(file);
								}
							}
						}

						if (files.length > 0 && onDropFilesRef.current) {
							event.preventDefault();
							const pos = view.state.selection.main.head;
							onDropFilesRef.current(files).then((urls) => {
								const text = urls.map(url => `![image](${url})`).join('\n');
								view.dispatch({
									changes: { from: pos, insert: text },
									selection: { anchor: pos + text.length }
								});
							}).catch(err => {
								console.error('Failed to upload files:', err);
							});
							return true;
						}
						return false;
					},
					drop: (event, view) => {
						event.preventDefault();
						const files = Array.from(event.dataTransfer?.files || []);
						if (files.length > 0 && onDropFilesRef.current) {
							const pos = view.posAtCoords({ x: event.clientX, y: event.clientY });
							if (pos !== null) {
								onDropFilesRef.current(files).then((urls) => {
									const text = urls.map(url => `![image](${url})`).join('\n');
									view.dispatch({
										changes: { from: pos, insert: text },
										selection: { anchor: pos + text.length }
									});
								}).catch(err => {
									console.error('Failed to upload files:', err);
								});
							}
						}
						return true;
					},
					dragover: (event) => {
						event.preventDefault();
						return true;
					}
				}),
			],
		});

		const view = new EditorView({
			state,
			parent: containerRef.current,
		});

		editorRef.current = view;

		return () => {
			view.destroy();
		};
	}, [initialContent]);

	// Update editor content when initialContent changes (without recreating the editor)
	useEffect(() => {
		if (editorRef.current && initialContent !== undefined) {
			const currentContent = editorRef.current.state.doc.toString();
			if (currentContent !== initialContent) {
				editorRef.current.dispatch({
					changes: {
						from: 0,
						to: currentContent.length,
						insert: initialContent,
					},
				});
			}
		}
	}, [initialContent]);

	return (
		<div
			ref={containerRef}
			style={{ height: "400px", border: "1px solid #ccc" }}
		/>
	);
}
