// server/admin/frontend/src/components/SearchBox.tsx
import React, { useState } from "react";
import { debounce } from "../utils";

interface SearchBoxProps {
	onSearch: (keyword: string) => void;
}

export default function SearchBox({ onSearch }: SearchBoxProps) {
	const [keyword, setKeyword] = useState("");

	const debouncedSearch = React.useMemo(
		() =>
			debounce((newKeyword: string) => {
				onSearch(newKeyword);
			}, 1000),
		[onSearch],
	);

	function handleInput(event: React.ChangeEvent<HTMLInputElement>) {
		const newKeyword = event.target.value;
		setKeyword(newKeyword);
		debouncedSearch(newKeyword);
	}

	const styles = {
		searchInput: {
			marginBottom: "1rem",
			width: "100%",
			borderRadius: "0.375rem",
			border: "1px solid #d1d5db",
			padding: "0.5rem",
		},
	};

	return (
		<input
			type="text"
			placeholder="Search entries..."
			style={styles.searchInput}
			value={keyword}
			onChange={handleInput}
		/>
	);
}

// server/admin/frontend/src/components/SearchBox.svelte
<script lang="ts">
import { debounce } from "../utils";
const { onSearch } = $props();
let keyword = "";

const debouncedSearch = debounce((newKeyword: string) => {
	onSearch(newKeyword);
}, 1000);

function onInput(event: Event) {
	const target = event.target as HTMLInputElement;
	if (target) {
		keyword = target.value;
	}
	debouncedSearch(keyword);
}
</script>

<input type="text" placeholder="Search entries..." class="search-input" oninput={onInput} />

<style>
	.search-input {
		margin-bottom: 1rem;
		width: 100%;
		border-radius: 0.375rem;
		border: 1px solid #d1d5db;
		padding: 0.5rem;
	}
</style>
