// server/admin/frontend/src/pages/TopPage.svelte
<script lang="ts">
import { onDestroy, onMount } from "svelte";
import { createAdminApiClient } from "../admin_api";
import AdminEntryCardItem from "../components/AdminEntryCardItem.svelte";
import SearchBox from "../components/SearchBox.svelte";
import type { GetLatestEntriesRow } from "../generated-client/model";

const api = createAdminApiClient();

let searchKeyword = $state("");

let allEntries: GetLatestEntriesRow[] = $state([]);
const filteredEntries: GetLatestEntriesRow[] = $derived.by(() => {
	if (searchKeyword === "") {
		return allEntries;
	}

	const lowerKeyword = searchKeyword.toLowerCase();
	return allEntries.filter(
		(entry) =>
			entry.Title?.toLowerCase()?.includes(lowerKeyword) ||
			entry.Body?.toLowerCase()?.includes(lowerKeyword),
	);
});

let isLoading = $state(false);
let hasMore = $state(true);
let loadInterval: ReturnType<typeof setInterval> | null = null;

function handleSearch(keyword: string) {
	searchKeyword = keyword;
}

async function loadMoreEntries() {
	if (!allEntries) {
		console.log("allEntries is not initialized yet");
		return;
	}
	console.log(`loadMoreEntries ${isLoading} ${hasMore} ${allEntries.length}`);
	if (isLoading || !hasMore) return;

	isLoading = true;

	const last_last_edited_at = allEntries[allEntries.length - 1]?.LastEditedAt;
	if (allEntries.length > 0 && !last_last_edited_at) {
		isLoading = false;
		hasMore = false;
		return;
	}

	try {
		console.log(`loadMoreEntries ${last_last_edited_at}`);
		console.log(allEntries);
		const rawEntries = await api.getLatestEntries(
			last_last_edited_at
				? {
						lastLastEditedAt: last_last_edited_at,
					}
				: {},
		);
		// Filter out any entries without a Path (note: PascalCase from API)
		const newEntries = (rawEntries || []).filter((entry) => entry?.Path);

		if (newEntries.length === 0) {
			console.log(
				`No more entries to load... stopping loading more entries. last_last_edited_at=${last_last_edited_at}`,
			);
			hasMore = false;
		} else {
			const existingPaths = allEntries.map((entry) => entry.Path);
			const addingNewEntries = newEntries.filter(
				(entry) => !existingPaths.includes(entry.Path),
			);
			if (addingNewEntries.length === 0) {
				console.log(
					`All entries are duplicated... stopping loading more entries. last_last_edited_at=${last_last_edited_at}, newEntries=${newEntries.map((entry) => entry.Title)}`,
				);
				hasMore = false;
			} else {
				console.log(
					`Adding new entries... last_last_edited_at=${last_last_edited_at}, newEntries=${newEntries.map((entry) => entry.Title)}`,
				);
				allEntries = [...allEntries, ...addingNewEntries];
			}
		}
	} catch (err) {
		hasMore = false;
		console.error(err);
	} finally {
		isLoading = false;
	}
}

async function handleKeydown(event: KeyboardEvent) {
	if (
		event.key === "c" &&
		!event.ctrlKey &&
		!event.altKey &&
		!event.metaKey &&
		!event.shiftKey
	) {
		event.preventDefault();
		event.stopPropagation();
		try {
			const response = await fetch("/admin/api/entry", {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify({}),
			});
			if (response.ok) {
				const data = await response.json();
				location.href = `/admin/entry/${data.path}`;
			} else {
				alert(
					`Failed to create new entry: ${response.status} ${response.statusText}`,
				);
			}
		} catch (err) {
			console.error(err);
			alert(`Failed to create new entry: ${err}`);
			return false;
		}
	}
	return true;
}

onMount(() => {
	window.addEventListener("keydown", handleKeydown);

	try {
		console.log("Loading entries...");
		isLoading = true;
		api.getLatestEntries().then((entries) => {
			console.log("Loaded entries", entries);
			// Filter out any entries without a Path (note: PascalCase from API)
			allEntries = (entries || []).filter((entry) => entry?.Path);
			isLoading = false;

			console.log("Start loading more entries...");
			// start loading more entries
			loadInterval = setInterval(() => {
				if (!isLoading && hasMore) {
					loadMoreEntries();
				}
			}, 10);
		});
	} catch (err) {
		console.error(err);
		alert(`Failed to load entries: ${err}`);
	}

	return () => {
		if (loadInterval) {
			clearInterval(loadInterval);
		}
		window.removeEventListener("keydown", handleKeydown);
	};
});

onDestroy(() => {
	if (loadInterval) {
		clearInterval(loadInterval);
	}
});
</script>

<div class="container">
    <SearchBox onSearch={handleSearch} />

    <div class="entry-list">
        {#each filteredEntries as entry, index (entry.Path || `index-${index}`)}
            <AdminEntryCardItem {entry} />
        {/each}
    </div>
    {#if isLoading || hasMore}
        <p class="loading-message">Loading more entries...</p>
    {/if}
    {#if !hasMore && allEntries.length > 0}
        <p class="loading-message">No more entries to load</p>
    {/if}
</div>

<style>
    .container {
        padding: 1rem;
        margin: 0 auto;
        max-width: 1200px;
    }

    .loading-message {
        margin-top: 1rem;
        text-align: center;
        color: #6b7280;
    }

    .entry-list {
        display: flex;
        flex-wrap: wrap;
        margin: auto;
        gap: 1rem;
        justify-content: flex-start;
        max-width: 1200px;
    }
</style>

// web/admin/src/pages/TopPage.tsx
import { Alert, Box, CircularProgress, Grid, Typography } from "@mui/material";
import { format } from "date-fns";
import React, { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { createAdminApiClient } from "../admin_api";
import AdminEntryCardItem from "../components/AdminEntryCardItem";
import SearchBox from "../components/SearchBox";
import type { GetLatestEntriesRow } from "../generated-client/model";

const api = createAdminApiClient();

export default function TopPage() {
	const navigate = useNavigate();
	const [searchKeyword, setSearchKeyword] = useState("");
	const [allEntries, setAllEntries] = useState<GetLatestEntriesRow[]>([]);
	const [isLoading, setIsLoading] = useState(false);
	const [hasMore, setHasMore] = useState(true);
	const [isInitialized, setIsInitialized] = useState(false);
	const loadingRef = useRef(false);

	const filteredEntries = React.useMemo(() => {
		if (searchKeyword === "") {
			return allEntries;
		}

		const lowerKeyword = searchKeyword.toLowerCase();
		return allEntries.filter(
			(entry) =>
				entry.Title?.toLowerCase()?.includes(lowerKeyword) ||
				entry.Body?.toLowerCase()?.includes(lowerKeyword),
		);
	}, [searchKeyword, allEntries]);

	function handleSearch(keyword: string) {
		setSearchKeyword(keyword);
	}

	const loadMoreEntries = React.useCallback(async () => {
		// Prevent concurrent loads
		if (loadingRef.current || !hasMore) {
			return;
		}

		loadingRef.current = true;
		setIsLoading(true);

		try {
			const lastEntry = allEntries[allEntries.length - 1];
			if (!lastEntry) {
				console.error("No entries loaded yet, loading initial entries");
				return;
			}
			const lastEditedAt = lastEntry.LastEditedAt;

			console.log(
				`Loading more entries... last_last_edited_at=${lastEditedAt} title=${lastEntry.Title}`,
			);

			const rawEntries = await api.getLatestEntries({
				last_last_edited_at: lastEditedAt,
			});

			// Filter out any entries without a Path
			const newEntries = (rawEntries || []).filter((entry) => entry?.Path);

			if (newEntries.length === 0) {
				console.log("No more entries to load");
				setHasMore(false);
			} else {
				// Filter out duplicates
				const existingPaths = new Set(allEntries.map((entry) => entry.Path));
				const uniqueNewEntries = newEntries.filter(
					(entry) => !existingPaths.has(entry.Path),
				);

				if (uniqueNewEntries.length === 0) {
					console.log(
						`All entries are duplicates, no more to load: ${newEntries.length}, ${newEntries[0].Title}`,
					);
					setHasMore(false);
				} else {
					console.log(`Adding ${uniqueNewEntries.length} new entries`);
					setAllEntries((prev) => [...prev, ...uniqueNewEntries]);
				}
			}
		} catch (err) {
			console.error("Failed to load more entries:", err);
			setHasMore(false);
		} finally {
			loadingRef.current = false;
			setIsLoading(false);
		}
	}, [allEntries, hasMore]);

	const handleKeydown = React.useCallback(
		async (event: KeyboardEvent) => {
			if (
				event.key === "c" &&
				!event.ctrlKey &&
				!event.altKey &&
				!event.metaKey &&
				!event.shiftKey
			) {
				event.preventDefault();
				event.stopPropagation();
				try {
					// Generate a placeholder title with current date/time
					const now = new Date();
					const placeholderTitle = format(
						now,
						"'New Entry' yyyy-MM-dd HH-mm-ss",
					);

					const data = await api.createEntry({ title: placeholderTitle });
					console.log(`New entry created: ${data.Path}`);
					navigate(`/admin/entry/${data.Path}`);
				} catch (err) {
					console.error("Error creating new entry:", err);
					alert(`Failed to create new entry: ${err}`);
				}
			}
		},
		[navigate],
	);

	// Initial load effect
	useEffect(() => {
		if (isInitialized) return;
		setIsInitialized(true);

		const loadInitial = async () => {
			if (isLoading) return;

			console.log("Loading initial entries...");
			setIsLoading(true);

			try {
				const entries = await api.getLatestEntries();

				console.log(`Loaded ${entries?.length || 0} initial entries`);
				const validEntries = (entries || []).filter((entry) => entry?.Path);
				console.log(
					`number of valid entries: ${validEntries?.length || 0} initial entries`,
				);
				setAllEntries(validEntries);
				setIsInitialized(true);

				// Only set hasMore if we got a full page of results
				// Assuming the API returns 20-50 items per page
				setHasMore(validEntries.length >= 20);
			} catch (err) {
				console.error("Failed to load initial entries:", err);
				setIsInitialized(true);
				setHasMore(false);
			} finally {
				setIsLoading(false);
			}
		};

		loadInitial();
	}, [isInitialized, isLoading]);

	// Load more entries using timeout
	useEffect(() => {
		if (!isInitialized || !hasMore || loadingRef.current) return;

		const timeoutId = setTimeout(() => {
			if (hasMore && !loadingRef.current) {
				loadMoreEntries();
			}
		}, 100);

		return () => {
			clearTimeout(timeoutId);
		};
	}, [isInitialized, hasMore, loadMoreEntries]);

	// Keyboard shortcuts
	useEffect(() => {
		window.addEventListener("keydown", handleKeydown);
		return () => {
			window.removeEventListener("keydown", handleKeydown);
		};
	}, [handleKeydown]);

	return (
		<Box sx={{ width: "100%" }}>
			<SearchBox onSearch={handleSearch} />

			<Grid container spacing={2}>
				{filteredEntries.map((entry) => (
					<Grid item xs={12} sm={6} md={4} lg={3} xl={2} key={entry.Path}>
						<AdminEntryCardItem entry={entry} />
					</Grid>
				))}
			</Grid>

			{isLoading && (
				<Box
					sx={{
						display: "flex",
						justifyContent: "center",
						alignItems: "center",
						mt: 4,
					}}
				>
					<CircularProgress />
					<Typography sx={{ ml: 2 }}>Loading more entries...</Typography>
				</Box>
			)}

			{!hasMore && allEntries.length > 0 && (
				<Box sx={{ display: "flex", justifyContent: "center", mt: 4 }}>
					<Typography color="text.secondary">
						No more entries to load
					</Typography>
				</Box>
			)}

			{!isLoading && allEntries.length === 0 && isInitialized && (
				<Box sx={{ display: "flex", justifyContent: "center", mt: 4 }}>
					<Alert severity="info">No entries found</Alert>
				</Box>
			)}
		</Box>
	);
}
