// server/admin/frontend/src/App.svelte
<script lang="ts">
import { Link, Route, Router } from "svelte-routing";
import Layout from "./Layout.svelte";
import NotFound from "./NotFound.svelte";
import TopPage from "./pages/TopPage.svelte";
import AdminEntryPage from "./pages/AdminEntryPage.svelte";
</script>

<Router>
    <Layout>
        <Route path="/admin/">
            <TopPage />
        </Route>
        <Route path="/admin/entry/*" let:params>
            <AdminEntryPage path={params['*']} />
        </Route>
        <Route path="/*" component={NotFound} />
    </Layout>
</Router>

// internal/admin/frontend/src/App.tsx
import { BrowserRouter, Route, Routes } from "react-router-dom";
import Layout from "./Layout";
import NotFound from "./NotFound";
import AdminEntryPage from "./pages/AdminEntryPage";
import TopPage from "./pages/TopPage";

export default function App() {
	return (
		<BrowserRouter>
			<Routes>
				<Route path="/" element={<Layout />}>
					<Route path="/admin/" element={<TopPage />} />
					<Route path="/admin/entry/*" element={<AdminEntryPage />} />
					<Route path="*" element={<NotFound />} />
				</Route>
			</Routes>
		</BrowserRouter>
	);
}
