// server/admin/frontend/src/pages/AdminEntryPage.svelte
<script lang="ts">
import { onMount } from "svelte";
import MarkdownEditor from "../components/MarkdownEditor.svelte";

import { createAdminApiClient } from "../admin_api";
import LinkPallet from "../components/LinkPallet.svelte";
import { extractLinks } from "../extractLinks";
import type {
	GetLatestEntriesRow,
	LinkPalletData,
} from "../generated-client/model";
import { debounce } from "../utils";

const { path } = $props();
const api = createAdminApiClient();
let entry: GetLatestEntriesRow = $state({});

let links: { [key: string]: string | null } = $state({});

let title: string = $state("");
let body: string = $state("");
let visibility = $state("private");
let currentLinks: string[] = $state([]);

let linkPallet: LinkPalletData = $state({
	links: [],
	twohops: [],
	newLinks: [],
});

onMount(async () => {
	try {
		entry = await api.getEntryByDynamicPath({
			path: encodeURIComponent(path),
		});

		title = entry.Title;
		body = entry.Body;
		visibility = entry.Visibility;
		currentLinks = extractLinks(entry.Body);
	} catch (e) {
		console.error("Failed to get entry:", e);
		if (e instanceof Error && e.message.includes("404")) {
			// maybe entry was deleted
			location.href = "/admin/";
		}
	}

	links = await api.getLinkedEntryPaths({ path: encodeURIComponent(path) });
	loadLinks();
});

let pageTitles: string[] = $state([]);

let isDirty = false;

function loadLinks() {
	api
		.getLinkPallet({ path: encodeURIComponent(path) })
		.then((data) => {
			console.log("Got link pallet data", data);
			linkPallet = data;
		})
		.catch((error) => {
			console.error("Failed to get links:", error);
		});
}

let message = $state("");
let messageType: "success" | "error" | "" = $state("");

let updatedMessage = $state("");

function showUpdatedMessage(text: string) {
	updatedMessage = text;
	setTimeout(() => {
		updatedMessage = "";
	}, 1000);
}

function clearMessage() {
	message = "";
	messageType = "";
}

function showMessage(type: "success" | "error", text: string) {
	messageType = type;
	message = text;
	setTimeout(() => {
		message = "";
		messageType = "";
	}, 5000); // Hide message after 5 seconds
}

async function handleDelete(event: Event) {
	event.preventDefault();

	const confirmed = confirm(
		`Are you sure you want to delete the entry "${title}"?`,
	);
	if (confirmed) {
		clearMessage();

		try {
			await api.deleteEntry({
				path: encodeURIComponent(entry.Path),
			});
			showMessage("success", "Entry deleted successfully");
			location.href = "/admin/";
		} catch (e) {
			console.log(e);
			showMessage("error", "Failed to delete entry");
		}
	}
}

async function handleRegenerateEntryImage(event: Event) {
	event.preventDefault();

	clearMessage();

	try {
		await api.regenerateEntryImage({
			path: encodeURIComponent(entry.Path),
		});
		showMessage("success", "Entry image regenerated successfully");
		location.href = "/admin/";
	} catch (e) {
		console.log(e);
		showMessage("error", "Failed to regenerate entry image");
	}
}

async function handleUpdateBody() {
	clearMessage();

	if (body === "") {
		showMessage("error", "Body cannot be empty");
		return;
	}

	try {
		await api.updateEntryBody(
			{ path: encodeURIComponent(path) },
			{
				body: body,
			},
		);

		showUpdatedMessage("Updated");
		isDirty = false; // Reset dirty flag on successful update
	} catch (e) {
		showMessage("error", "Failed to update entry body");
		console.error("Failed to update entry body:", e);
	}
}

async function handleUpdateTitle() {
	clearMessage();
	if (title === "") {
		showMessage("error", "Title cannot be empty");
		return;
	}

	try {
		await api.updateEntryTitle(
			{ path: encodeURIComponent(path) },
			{
				title,
			},
		);

		showMessage("success", "Entry updated successfully");
		isDirty = false; // Reset dirty flag on successful update
	} catch (e) {
		showMessage("error", "Failed to update entry title");
		console.error("Failed to update entry title:", e);
	}
}

async function createNewEntry(title: string): Promise<void> {
	clearMessage();

	try {
		const data = await api.createEntry({
			createEntryRequest: {
				title,
			},
		});
		location.href = `/admin/entry/${data.Path}`;
	} catch (error) {
		console.error("Failed to create new entry:", error);
		showMessage(
			"error",
			`Failed to create new entry: ${error instanceof Error ? error.message : error}`,
		);
	}
}

// デバウンスした自動保存関数
const debouncedUpdateBody = debounce(() => {
	handleUpdateBody();
}, 800);

// title related.
const debouncedTitleUpdate = debounce(() => {
	handleUpdateTitle();
}, 500);

function handleTitleInput() {
	isDirty = true;
	debouncedTitleUpdate();
}

// 入力イベントや変更イベントにデバウンスされた関数をバインド
function handleInputBody() {
	isDirty = true;
	debouncedUpdateBody();

	const newLinks = extractLinks(body);
	if (currentLinks !== newLinks) {
		currentLinks = newLinks;
		loadLinks();
	}
}

function toggleVisibility(event: Event) {
	event.preventDefault();
	event.stopPropagation();

	const newVisibility = visibility === "private" ? "public" : "private";

	if (
		!confirm("Are you sure you want to change the visibility of this entry?")
	) {
		return;
	}

	console.log("Updating visibility to", newVisibility);

	api
		.updateEntryVisibility(
			{ path: encodeURIComponent(entry.Path) },
			{
				visibility: newVisibility,
			},
		)
		.then((data) => {
			visibility = data.Visibility;
		})
		.catch((error) => {
			console.error("Failed to update visibility:", error);
			showMessage("error", `Failed to update visibility: ${error.message}`);
		});
}

// TODO: 未保存の変更がある場合に警告を表示する
// beforeNavigate(({ cancel }) => {
//     if (isDirty && !confirm('You have unsaved changes. Are you sure you want to leave?')) {
//         cancel();
//     }
// });

function getEditDistance(a: string, b: string): number {
	const dp = Array.from({ length: a.length + 1 }, () =>
		Array(b.length + 1).fill(0),
	);

	for (let i = 0; i <= a.length; i++) dp[i][0] = i;
	for (let j = 0; j <= b.length; j++) dp[0][j] = j;

	for (let i = 1; i <= a.length; i++) {
		for (let j = 1; j <= b.length; j++) {
			if (a[i - 1] === b[j - 1]) {
				dp[i][j] = dp[i - 1][j - 1];
			} else {
				dp[i][j] =
					Math.min(
						dp[i - 1][j], // 削除
						dp[i][j - 1], // 挿入
						dp[i - 1][j - 1], // 置換
					) + 1;
			}
		}
	}

	return dp[a.length][b.length];
}

// 定期的に本文情報を再取得する。
// 他のユーザーが大幅に変更していた場合は警告を表示し、リロードを促す。
// TODO: 編集不可状態とする。
function checkOtherUsersUpdate() {
	api
		.getEntryByDynamicPath({
			path: entry.Path,
		})
		.then((data) => {
			// 本文が短いときは消えてもダメージ少ないので無視
			if (data.Body && data.Body.length > 100 && !isDirty) {
				const threshold = Math.max(body.length, data.Body.length) * 0.1; // 10%以上の変更で判定
				const editDistance = getEditDistance(body, data.Body);
				if (editDistance > threshold) {
					if (
						confirm(
							`他のユーザーが大幅に変更しました。リロードしてください。 ${editDistance} > ${threshold}`,
						)
					) {
						location.reload();
					}
				}
			}
		});
}

onMount(() => {
	// get page titles
	setTimeout(async () => {
		pageTitles = await api.getAllEntryTitles();
	}, 0);

	document.addEventListener("visibilitychange", () => {
		checkOtherUsersUpdate();
	});
});

function selectIfPlaceholder(target: HTMLInputElement) {
	if (/^2\d+$/.test(target.value)) {
		target.select(); // 入力値を全選択
	}
}
</script>

<div class="parent">
    <div class="container {entry.Visibility === 'private' ? 'private' : ''}">
        <div class="left-pane">
            <form class="form">
                <div class="title-container">
                    <input
                            id="title"
                            name="title"
                            type="text"
                            class="input"
                            bind:value={title}
                            onfocus={(event) => selectIfPlaceholder(event.target as HTMLInputElement)}
                            oninput={handleTitleInput}
                            required
                    />
                    <button class="visibility-icon" onclick={(event) => toggleVisibility(event)}
                    >{visibility === 'private' ? '🔒️' : '🌍'}</button
                    >
                </div>

                <div class="editor">
                    <input type="hidden" name="body" bind:value={body}/>
                    <MarkdownEditor
                            initialContent=""
                            content={body}
                            onUpdateText={(content) => {
                                if (content !== body) {
                                    body = content;
                                    handleInputBody(); // エディタ更新時にデバウンスされた更新をトリガー
                                }
                            }}
                            existsEntryByTitle={(title) => {
                                return !!links[title.toLowerCase()];
                            }}
                            onClickEntry={(title) => {
                                if (links[title.toLowerCase()]) {
                                    location.href = '/admin/entry/' + links[title.toLowerCase()];
                                } else {
                                    createNewEntry(title);
                                }
                            }}
                            onSave={() => {
                                handleUpdateBody();
                            }}
                            {pageTitles}
                    />
                </div>
            </form>
        </div>

        <div class="right-pane">
            <div class="button-container">
                <button type="submit" class="delete-button" onclick={handleDelete}> Delete</button>
                <button type="submit" class="regenerate-button" onclick={handleRegenerateEntryImage}> Regenerate entry_image</button>
            </div>

            <!-- link to the user side page -->
            {#if visibility === 'public'}
                <div class="link-container">
                    <a href="/entry/{entry.Path}" class="link">Go to User Side Page</a>
                </div>
            {/if}

            {#if updatedMessage !== ''}
                <div class="updated-message">
                    {updatedMessage}
                </div>
            {/if}
        </div>
    </div>

    {#if message}
        <div class="popup-message {messageType}">
            <p>{message}</p>
        </div>
    {/if}

    <div class="link-pallet">
        <LinkPallet {linkPallet} />
    </div>
</div>

<style>
    .link-pallet {
        margin: auto;
        max-width: 1200px;
    }

    .container {
        display: flex;
        flex-wrap: wrap;
        max-width: 1200px;
        margin: auto;
    }

    .container.private {
        background-color: #e5e7eb;
    }

    .left-pane {
        flex: 1;
        min-width: 300px;
        max-width: 800px;
    }

    .right-pane {
        margin-left: 1rem; /* Add some space between the panes */
        max-width: 300px;

        .link-container {
            margin-top: 80px;
        }

        button, a {
            display: block;
            border-radius: 0.375rem;
            border: 1px solid antiquewhite;
            padding: 0.5rem 1rem;
            margin-top: 4px;
        }

        .delete-button {
            background-color: #ef4444;
            color: white;

            &:hover {
                background-color: #dc2626;
            }
        }

        .link {
            background-color: #10b981;
            color: white;
            text-decoration: none;

            &:hover {
                text-decoration: underline;
            }
        }
    }

    .form {
        display: flex;
        flex-direction: column;
        gap: 1rem;
        padding: 1rem;
        max-width: 800px;
    }

    .input {
        width: calc(100% - 2rem); /* Adjust width to make space for the icon */
        border-radius: 0.375rem;
        border: 1px solid #d1d5db;
        padding: 0.5rem;
    }

    .title-container {
        display: flex;
        align-items: center;
    }

    .visibility-icon {
        border: 0;
        background-color: transparent;
        margin-left: 0.5rem;
        font-size: 1.5rem;
        cursor: pointer;
    }

    .editor {
        border: 1px solid #d1d5db;
        border-radius: 0.25rem;
        height: 400px;
        overflow-y: scroll;
    }

    .popup-message {
        position: fixed;
        bottom: 1rem;
        right: 1rem;
        padding: 1rem;
        border-radius: 0.375rem;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        z-index: 1000;
    }

    .popup-message.success {
        background-color: #10b981;
        color: white;
    }

    .popup-message.error {
        background-color: #ef4444;
        color: white;
    }

    @media (max-width: 600px) {
        .container {
            flex-direction: column;
        }

        .right-pane {
            margin-left: 0;
            margin-top: 1rem; /* Add some space between the panes */
        }
    }

    .updated-message {
        color: #10b981;
    }
</style>

// server/admin/frontend/src/pages/AdminEntryPage.tsx
import React, { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
import { createAdminApiClient } from "../admin_api";
import LinkPallet from "../components/LinkPallet";
import MarkdownEditor from "../components/MarkdownEditor";
import { extractLinks } from "../extractLinks";
import type {
	GetLatestEntriesRow,
	LinkPalletData,
} from "../generated-client/model";
import { debounce } from "../utils";

const api = createAdminApiClient();

export default function AdminEntryPage() {
	const location = useLocation();
	const path = location.pathname.replace("/admin/entry/", "");

	const [entry, setEntry] = useState<GetLatestEntriesRow>(
		{} as GetLatestEntriesRow,
	);
	const [, setLinks] = useState<{ [key: string]: string | null }>({});
	const [title, setTitle] = useState("");
	const [body, setBody] = useState("");
	const [visibility, setVisibility] = useState("private");
	const [currentLinks, setCurrentLinks] = useState<string[]>([]);
	const [linkPallet, setLinkPallet] = useState<LinkPalletData>({
		links: [],
		twohops: [],
		newLinks: [],
	});
	const [, setMessage] = useState("");
	const [, setMessageType] = useState<"success" | "error" | "">("");
	const [updatedMessage, setUpdatedMessage] = useState("");
	const [, setIsDirty] = useState(false);

	const showUpdatedMessage = React.useCallback((text: string) => {
		setUpdatedMessage(text);
		setTimeout(() => {
			setUpdatedMessage("");
		}, 1000);
	}, []);

	const clearMessage = React.useCallback(() => {
		setMessage("");
		setMessageType("");
	}, []);

	const showMessage = React.useCallback((type: "success" | "error", text: string) => {
		setMessageType(type);
		setMessage(text);
		setTimeout(() => {
			setMessage("");
			setMessageType("");
		}, 5000);
	}, []);

	const loadLinks = React.useCallback(() => {
		api
			.getLinkPallet({ path: encodeURIComponent(path) })
			.then((data) => {
				console.log("Got link pallet data", data);
				setLinkPallet(data);
			})
			.catch((error) => {
				console.error("Failed to get links:", error);
			});
	}, [path]);

	async function handleDelete(event: React.MouseEvent) {
		event.preventDefault();

		const confirmed = confirm(
			`Are you sure you want to delete the entry "${title}"?`,
		);
		if (confirmed) {
			clearMessage();

			try {
				await api.deleteEntry({
					path: encodeURIComponent(entry.Path),
				});
				showMessage("success", "Entry deleted successfully");
				location.href = "/admin/";
			} catch (e) {
				console.log(e);
				showMessage("error", "Failed to delete entry");
			}
		}
	}

	async function handleRegenerateEntryImage(event: React.MouseEvent) {
		event.preventDefault();

		clearMessage();

		try {
			await api.regenerateEntryImage({
				path: encodeURIComponent(entry.Path),
			});
			showMessage("success", "Entry image regenerated successfully");
			location.href = "/admin/";
		} catch (e) {
			console.log(e);
			showMessage("error", "Failed to regenerate entry image");
		}
	}

	const handleUpdateBody = React.useCallback(async () => {
		clearMessage();

		if (body === "") {
			showMessage("error", "Body cannot be empty");
			return;
		}

		try {
			await api.updateEntryBody(
				{ path: encodeURIComponent(path) },
				{
					body: body,
				},
			);

			showUpdatedMessage("Updated");
			setIsDirty(false);
		} catch (e) {
			showMessage("error", "Failed to update entry body");
			console.error("Failed to update entry body:", e);
		}
	}, [body, path, clearMessage, showMessage, showUpdatedMessage]);

	const handleUpdateTitle = React.useCallback(async () => {
		clearMessage();
		if (title === "") {
			showMessage("error", "Title cannot be empty");
			return;
		}

		try {
			await api.updateEntryTitle(
				{ path: encodeURIComponent(path) },
				{
					title,
				},
			);

			showMessage("success", "Entry updated successfully");
			setIsDirty(false);
		} catch (e) {
			showMessage("error", "Failed to update entry title");
			console.error("Failed to update entry title:", e);
		}
	}, [title, path, clearMessage, showMessage]);

	const debouncedUpdateBody = React.useMemo(
		() => debounce(() => handleUpdateBody(), 800),
		[handleUpdateBody],
	);

	const debouncedTitleUpdate = React.useMemo(
		() => debounce(() => handleUpdateTitle(), 500),
		[handleUpdateTitle],
	);

	const handleInputBody = React.useCallback(() => {
		setIsDirty(true);
		debouncedUpdateBody();

		const newLinks = extractLinks(body);
		if (JSON.stringify(currentLinks) !== JSON.stringify(newLinks)) {
			setCurrentLinks(newLinks);
			loadLinks();
		}
	}, [body, currentLinks, debouncedUpdateBody, loadLinks]);

	function toggleVisibility(event: React.MouseEvent) {
		event.preventDefault();
		event.stopPropagation();

		const newVisibility = visibility === "private" ? "public" : "private";

		if (
			!confirm("Are you sure you want to change the visibility of this entry?")
		) {
			return;
		}

		console.log("Updating visibility to", newVisibility);

		api
			.updateEntryVisibility(
				{ path: encodeURIComponent(entry.Path) },
				{
					visibility: newVisibility,
				},
			)
			.then((data) => {
				setVisibility(data.Visibility);
			})
			.catch((error) => {
				console.error("Failed to update visibility:", error);
				showMessage("error", `Failed to update visibility: ${error.message}`);
			});
	}

	useEffect(() => {
		const loadEntry = async () => {
			try {
				const loadedEntry = await api.getEntryByDynamicPath({
					path: encodeURIComponent(path),
				});
				setEntry(loadedEntry);
				setTitle(loadedEntry.Title);
				setBody(loadedEntry.Body);
				setVisibility(loadedEntry.Visibility);
				setCurrentLinks(extractLinks(loadedEntry.Body));
			} catch (e) {
				console.error("Failed to get entry:", e);
				if (e instanceof Error && e.message.includes("404")) {
					location.href = "/admin/";
				}
			}
		};

		loadEntry();
		api.getLinkedEntryPaths({ path: encodeURIComponent(path) }).then(setLinks);
		loadLinks();
	}, [path, loadLinks, location]);

	const styles = {
		parent: {},
		container: {
			backgroundColor: entry.Visibility === "private" ? "#f3f4f6" : "white",
			minHeight: "100vh",
		},
		leftPane: {
			float: "left" as const,
			width: "49%",
			padding: "1rem",
		},
		rightPane: {
			float: "right" as const,
			width: "49%",
			padding: "1rem",
		},
		form: {},
		titleContainer: {
			marginBottom: "1rem",
		},
		input: {
			width: "100%",
			padding: "0.5rem",
			border: "1px solid #d1d5db",
			borderRadius: "0.25rem",
		},
		label: {
			display: "block",
			marginBottom: "0.5rem",
			fontWeight: "bold",
		},
		bodyContainer: {
			marginBottom: "1rem",
		},
		editor: {
			minHeight: "400px",
			border: "1px solid #d1d5db",
			borderRadius: "0.25rem",
		},
		visibilityContainer: {
			marginBottom: "1rem",
		},
		buttonContainer: {
			marginTop: "1rem",
			display: "flex",
			gap: "1rem",
		},
		deleteButton: {
			backgroundColor: "#ef4444",
			color: "white",
			padding: "0.5rem 1rem",
			border: "none",
			borderRadius: "0.25rem",
			cursor: "pointer",
		},
		regenerateButton: {
			backgroundColor: "#3b82f6",
			color: "white",
			padding: "0.5rem 1rem",
			border: "none",
			borderRadius: "0.25rem",
			cursor: "pointer",
		},
		linkContainer: {
			marginTop: "1rem",
		},
		link: {
			color: "#3b82f6",
			textDecoration: "underline",
		},
		updatedMessage: {
			position: "fixed" as const,
			top: "20px",
			right: "20px",
			backgroundColor: "#10b981",
			color: "white",
			padding: "0.5rem 1rem",
			borderRadius: "0.25rem",
		},
	};

	return (
		<div style={styles.parent}>
			<div style={styles.container}>
				<div style={styles.leftPane}>
					<form style={styles.form}>
						<div style={styles.titleContainer}>
							<input
								name="title"
								type="text"
								style={styles.input}
								value={title}
								onChange={(e) => {
									setTitle(e.target.value);
									setIsDirty(true);
									debouncedTitleUpdate();
								}}
								placeholder="Entry Title"
							/>
						</div>

						<div style={styles.bodyContainer}>
							<label htmlFor="body" style={styles.label}>
								Body
							</label>
							<div style={styles.editor}>
								<MarkdownEditor
									initialContent={body}
									onUpdateText={(text) => {
										setBody(text);
										handleInputBody();
									}}
								/>
							</div>
						</div>

						<div style={styles.visibilityContainer}>
							<label style={styles.label}>
								Visibility: {visibility}
								<button
									type="button"
									onClick={toggleVisibility}
									style={{ marginLeft: "1rem" }}
								>
									Toggle
								</button>
							</label>
						</div>
					</form>

					<div style={styles.buttonContainer}>
						<button
							type="submit"
							style={styles.deleteButton}
							onClick={handleDelete}
						>
							Delete
						</button>
						<button
							type="submit"
							style={styles.regenerateButton}
							onClick={handleRegenerateEntryImage}
						>
							Regenerate entry_image
						</button>
					</div>

					{visibility === "public" && (
						<div style={styles.linkContainer}>
							<a href={`/entry/${entry.Path}`} style={styles.link}>
								Go to User Side Page
							</a>
						</div>
					)}

					{updatedMessage !== "" && (
						<div style={styles.updatedMessage}>{updatedMessage}</div>
					)}
				</div>

				<div style={styles.rightPane}>
					<LinkPallet linkPallet={linkPallet} />
				</div>
			</div>
		</div>
	);
}
